
const jobGradingData = [
    {
        occupationalLevel: 'Top Management/ Executives',
        patersonClassic: ['F+1', 'F+2', 'F+3', 'F+4', 'F+5'],
        patersonModern: ['G Band'],
        reMeasure: ['300-349'],
        hayUnits: ['3581-7160'],
        hayDecisionTree: ['1++'],
        peromnes: [],
        task: [],
        jEasy: [],
        description: 'Controls the functional integration of the business. Determines the overall strategy and objectives of the business. Directs the company into the future. The nature of the work and focus is long-term. Sign-off on policy or strategy',
    },
    {
        occupationalLevel: 'Senior Management',
        patersonClassic: ['F1', 'F2', 'F3', 'F4', 'F5'],
        patersonModern: ['E Lower', 'E Upper'],
        reMeasure: ['200-249'],
        hayUnits: ['735-1800'],
        hayDecisionTree: ['175-224'],
        peromnes: ['4', '3', '2'],
        task: ['18-22'],
        jEasy: ['5a', '5b', '5c', '5d', '5e'],
        description: 'Knowledge of entire business area/BU/company or group. Provide inputs for/formulation of the overall Organisational strategy. Translates the overall strategy into business plans for BU/Functional Unit, thereby operationalising organisational strategy. Implements and manages business plan, goals and objectives and ensures the achievement of overall key Organisational/BU/Functional outputs. Manages the development of innovation and change',
    },
    {
        occupationalLevel: 'Professionally Qualified & experienced specialists/mid-management',
        patersonClassic: ['D1', 'D2', 'D3', 'D4', 'D5'],
        patersonModern: ['D Lower', 'D Upper'],
        reMeasure: ['150-199'],
        hayUnits: ['371-734'],
        hayDecisionTree: ['125-174'],
        peromnes: ['7', '6', '5', '4'],
        task: ['14-18'],
        jEasy: ['4a', '4b', '4c', '4d', '4e'],
        description: 'Professional knowledge of sub-discipline or discipline. Provide input in the formulation of Organisational/Functional Unit business plans. Formulate and implement departmental/team plans that will support the BU business plans. Optimisation of resources (finances, people, material, information and technology) to achieve given objectives in most productive and cost effective way',
    },
    {
        occupationalLevel: 'Skilled Technical & Academically Qualified/ Junior Management/ Supervisors/ Foremen/ Superintendents',
        patersonClassic: ['C1', 'C2', 'C3', 'C4', 'C5'],
        patersonModern: ['C Lower', 'C Upper'],
        reMeasure: ['100-149'],
        hayUnits: ['192-370'],
        hayDecisionTree: ['75-124'],
        peromnes: ['11', '10', '9', '8', '7'],
        task: ['9-13'],
        jEasy: ['3a', '3b', '3c', '3d', '3e'],
        description: 'Applies broad knowledge of products, techniques and processes. Evaluates procedures and applies previous experience. A good solution can usually be found. Determines own priorities. What has to be done is stipulated; but may require initiative in terms of how it should be done',
    },
    {
        occupationalLevel: 'Semi-Skilled & discretionary decision-making',
        patersonClassic: ['B1', 'B2', 'B3', 'B4', 'B5'],
        patersonModern: ['B Lower', 'B Upper'],
        reMeasure: ['50-99'],
        hayUnits: ['85-191'],
        hayDecisionTree: ['25-74'],
        peromnes: ['15', '14', '13', '12', '11'],
        task: ['4-8'],
        jEasy: ['2a', '2b', '2c', '2d', '2e'],
        description: 'Accountable for direct product, process or service quality. Incremental improvement of existing processes and procedures according to clear guidelines. Choosing of correct action on the basis of set standards, training procedures and past experience',
    },
    {
        occupationalLevel: 'Unskilled & defined decision-making',
        patersonClassic: ['A1', 'A2', 'A3'],
        patersonModern: ['A'],
        reMeasure: ['20-49'],
        hayUnits: ['54-84'],
        hayDecisionTree: ['0-24'],
        peromnes: ['19', '18', '17', '16'],
        task: ['1-3'],
        jEasy: ['1a', '1b', '1c'],
        description: 'Steps to accomplish work or processes are clearly defined and understood. Tasks are sometimes repetitive and uncomplicated and the work cycle is short',
    },
];

export default jobGradingData;